### ISSUE TITLE
The different between ingester and client

### ISSUE THREAD

**Issue by tisonkun** [GreptimeTeam/greptimedb-ingester-java#31]
See https://github.com/GreptimeTeam/greptimedb-client-java.

As in the Golang case, we archive client for recommending ingester. Currently, for Java, both repos seem maintained. Let's give a sentence for what we want to do.

cc @fengjiachun

**Comment by fengjiachun** [comment]
https://github.com/GreptimeTeam/greptimedb-client-java/pull/67

 I am going to  archive `greptimedb-client-java` after this pr be merged.
