### ISSUE TITLE
Version strategy or semantic?

### ISSUE THREAD

**Issue by tisonkun** [GreptimeTeam/greptimedb-ingester-java#34]
I can see that we're releasing 0.7.2, while there is no 0.7.0 for GreptimeDB now.

I wonder what is the version strategy for this ingester lib, or the version semantic. For example, 0.7.2 ingester-java should be compatible with what version range of GreptimeDB?

**Comment by fengjiachun** [comment]
Roughly this idea: DB 0.x.y1 -> SDK 0.x.y2

The version 0.7 of db has not been released yet, but the API is already stable, so I have released version 0.7 of the SDK in advance.

**Comment by tisonkun** [comment]
Thank you!
